name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Composer Deps
      run: make install

    - name: Copy .env file
      run: cp .env.example .env

    - name: Start Laravel Sail
      run: make up-wait

    - name: Generate Application Key
      run: make key

    - name: Run Migrations
      run: make migrate

    - name: Run NPM Install
      run: make npm-install

    - name: Run Vite Build
      run: make vite-build

    - name: Run Tests
      run: make test

    - name: Run Static Analysis
      run: make stan

    - name: Run Lint
      run: make lint
